/* LISTE des ASSIGNMENTS d'un ETUDIANT [PAGINATION] */

/* LISTE des ASSIGNMENTS d'un PROFESSEUR [PAGINATION] */

/* RECHERCHE par [PROFESSEUR - ETUDIANT - selon l'utilisateur connecté] - MATIERE - DATE de CRÉATION - DATE de RENDU [PAGINATION] */

/* LISTE de TOUS LES ASSIGNMENTS [ADMINISTRATEUR - PAGINATION] */

/* AJOUT D'UN NOUVEL ASSIGNMENT */

/* MODIFICATION D'UN ASSIGNMENT (Si l'assignment est rendu => Envoyé un email à l'ETUDIANT) */

/* EXPORTATION PDF du RELEVÉ de NOTE d'un ETUDIANT */